[project]
name = "tunesback"
version = "0.1.0"
dependencies = [
  "flet>=0.28.3",
  "pandas",
  "python-dateutil"
]

[tool.flet]
product = "TunesBack"
copyright = "Copyright Â© 2025 Peter Jin"

[tool.flet.app]
module = "app.py"
assets_dir = "assets"

[tool.flet.macos]
entitlement."com.apple.security.files.user-selected.read-only" = true
